status = [
  "ci/circleci: lint",
  "ci/circleci: test",
  "ci/circleci: build-extension",
  "t-lint-src",
  "t-test-src",
  "build-src"
]
# Avoid including verbose details from PR bodies
cut_body_after = "\n---\n"
block_labels = ["bors-dont-merge"]
delete_merged_branches = true
